In [1]:
import cv2

In [2]:
img = cv2.imread('C:\\Users\\91976\\OneDrive\\Desktop\\india-map.jpg')

In [3]:
img

array([[[229, 229, 229],
        [228, 228, 228],
        [227, 227, 227],
        ...,
        [228, 228, 228],
        [228, 228, 228],
        [228, 228, 228]],

       [[229, 229, 229],
        [228, 228, 228],
        [227, 227, 227],
        ...,
        [228, 228, 228],
        [228, 228, 228],
        [228, 228, 228]],

       [[228, 228, 228],
        [228, 228, 228],
        [227, 227, 227],
        ...,
        [228, 228, 228],
        [228, 228, 228],
        [228, 228, 228]],

       ...,

       [[226, 234, 224],
        [224, 228, 223],
        [226, 226, 226],
        ...,
        [228, 228, 228],
        [228, 228, 228],
        [228, 228, 228]],

       [[232, 232, 232],
        [232, 232, 232],
        [232, 232, 232],
        ...,
        [231, 231, 231],
        [231, 231, 231],
        [231, 231, 231]],

       [[233, 233, 233],
        [233, 233, 233],
        [233, 233, 233],
        ...,
        [231, 231, 231],
        [231, 231, 231],
        [231, 231, 231]]

In [4]:
img.shape

(834, 700, 3)

In [5]:
cv2.imshow('india window',img)
cv2.waitKey(-1)

-1

## To convert image to grey-scale(black n white)

In [6]:
cv2.imshow('india window',img)
cv2.waitKey(-1)

-1

In [7]:
img_grey = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

In [8]:
img.shape

(834, 700, 3)

In [9]:
img_grey.shape

(834, 700)

In [10]:
cv2.imshow('India Grey', img_grey)
cv2.waitKey(-1)

-1

## Changing Image Color

In [11]:
cv2.imshow('india window',img)
cv2.waitKey(-1)

-1

In [12]:
img.shape

(834, 700, 3)

In [13]:
import numpy as np

In [14]:
ary1 = np.random.randint(10,50,(2,4,6))

In [15]:
ary1

array([[[44, 36, 22, 11, 47, 35],
        [28, 34, 23, 30, 37, 35],
        [44, 21, 43, 35, 42, 37],
        [15, 29, 35, 32, 39, 26]],

       [[26, 39, 26, 33, 30, 12],
        [20, 28, 21, 46, 32, 33],
        [35, 23, 18, 31, 22, 19],
        [46, 30, 39, 27, 16, 49]]])

In [16]:
ary1.shape

(2, 4, 6)

In [17]:
img.shape

(834, 700, 3)

In [18]:
img_0 = img.copy()

In [19]:
img_1 = img.copy()

In [20]:
img_2 = img.copy()

In [21]:
cv2.imshow('india window',img_0)
cv2.waitKey(-1)

-1

In [22]:
cv2.imshow('india window',img_1)
cv2.waitKey(-1)

-1

In [23]:
cv2.imshow('india window',img_2)
cv2.waitKey(-1)

-1

### 1. Red is zero

In [24]:
img_0[ : , : , 0] = 0
# removed red color

In [25]:
cv2.imshow('img_0 window',img_0)
cv2.waitKey(-1)

-1

### 2. Green is Zero

In [26]:
img_1[ : , : , 1] = 0
# removed green color

In [27]:
cv2.imshow('img_1 window',img_1)
cv2.waitKey(-1)

-1

### 3. Blue is Zero

In [28]:
img_2[ : , : , 2] = 0
# removed blue color

In [29]:
cv2.imshow('img_2 window',img_2)
cv2.waitKey(-1)

-1

In [30]:
cv2.imshow('india window',img)
cv2.waitKey(-1)

-1

In [32]:
imgstack = np.hstack((img, img_0, img_1, img_2))

In [33]:
cv2.imshow('imgstack window',imgstack)
cv2.waitKey(-1)

-1

## Image Resize

In [34]:
img

array([[[229, 229, 229],
        [228, 228, 228],
        [227, 227, 227],
        ...,
        [228, 228, 228],
        [228, 228, 228],
        [228, 228, 228]],

       [[229, 229, 229],
        [228, 228, 228],
        [227, 227, 227],
        ...,
        [228, 228, 228],
        [228, 228, 228],
        [228, 228, 228]],

       [[228, 228, 228],
        [228, 228, 228],
        [227, 227, 227],
        ...,
        [228, 228, 228],
        [228, 228, 228],
        [228, 228, 228]],

       ...,

       [[226, 234, 224],
        [224, 228, 223],
        [226, 226, 226],
        ...,
        [228, 228, 228],
        [228, 228, 228],
        [228, 228, 228]],

       [[232, 232, 232],
        [232, 232, 232],
        [232, 232, 232],
        ...,
        [231, 231, 231],
        [231, 231, 231],
        [231, 231, 231]],

       [[233, 233, 233],
        [233, 233, 233],
        [233, 233, 233],
        ...,
        [231, 231, 231],
        [231, 231, 231],
        [231, 231, 231]]

In [35]:
cv2.imshow('india window',img)
cv2.waitKey(-1)

-1

In [36]:
img.shape

(834, 700, 3)

In [50]:
img_small = cv2.resize(img, (400,500))

In [51]:
img_small.shape

(500, 400, 3)

In [52]:
cv2.imshow('img_small window',img_small)
cv2.waitKey(-1)

-1

In [53]:
img_big = cv2.resize(img, (900,1000))

In [54]:
img_big.shape

(1000, 900, 3)

In [55]:
cv2.imshow('img_big window',img_big)
cv2.waitKey(-1)

-1

### Saving Image

In [56]:
cv2.imwrite('india.jpg', img)

True

In [58]:
cv2.imwrite('india_small.jpg', img_small)

True

In [59]:
cv2.imwrite('india_big.jpg', img_big)

True

### Reshape to half

In [60]:
img.shape

(834, 700, 3)

In [61]:
img.shape[0]//2

417

In [62]:
img.shape[1]//2

350

In [63]:
img_half = cv2.resize(img, (img.shape[1]//2,img.shape[0]//2))

In [64]:
img_half.shape

(417, 350, 3)

In [65]:
cv2.imshow('img_half window',img_half)
cv2.waitKey(-1)

-1

## Image Flip

In [66]:
img

array([[[229, 229, 229],
        [228, 228, 228],
        [227, 227, 227],
        ...,
        [228, 228, 228],
        [228, 228, 228],
        [228, 228, 228]],

       [[229, 229, 229],
        [228, 228, 228],
        [227, 227, 227],
        ...,
        [228, 228, 228],
        [228, 228, 228],
        [228, 228, 228]],

       [[228, 228, 228],
        [228, 228, 228],
        [227, 227, 227],
        ...,
        [228, 228, 228],
        [228, 228, 228],
        [228, 228, 228]],

       ...,

       [[226, 234, 224],
        [224, 228, 223],
        [226, 226, 226],
        ...,
        [228, 228, 228],
        [228, 228, 228],
        [228, 228, 228]],

       [[232, 232, 232],
        [232, 232, 232],
        [232, 232, 232],
        ...,
        [231, 231, 231],
        [231, 231, 231],
        [231, 231, 231]],

       [[233, 233, 233],
        [233, 233, 233],
        [233, 233, 233],
        ...,
        [231, 231, 231],
        [231, 231, 231],
        [231, 231, 231]]

In [67]:
cv2.imshow('india window',img)
cv2.waitKey(-1)

-1

In [68]:
img_flip_0 = cv2.flip(img, 0)
# it's like water image

In [69]:
cv2.imshow('img_flip_0 window',img_flip_0)
cv2.waitKey(-1)

-1

In [70]:
img_flip_1 = cv2.flip(img, 1)
# it's like mirror image but on left side

In [72]:
cv2.imshow('img_flip_1 window',img_flip_1)
cv2.waitKey(-1)

-1

## Crop Image

In [73]:
img.shape

(834, 700, 3)

In [74]:
cv2.imshow('india window',img)
cv2.waitKey(-1)

-1

In [75]:
img_crop = img[0:300, 0:300]

In [76]:
img_crop.shape

(300, 300, 3)

In [77]:
cv2.imshow('img_crop window',img_crop)
cv2.waitKey(-1)

-1